version: "3.8"
services:
  web:
    build:
      content: .
      dockerfile: dockerfile
    container_name: app
    ports:
      - "5001:5000"
    volumes:
      - .:/project
    environment: 
      FLASK_ENV: development
